Layout/ParameterAlignment:
  Enabled: true

Layout/HashAlignment:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Layout/LineLength:
  Max: 100
  AutoCorrect: true

Metrics/AbcSize:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 40

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 300

Lint/UselessAssignment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/Documentation:
Enabled: false
