Layout/ParameterAlignment:
  Enabled: true

Layout/HashAlignment:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Layout/LineLength:
  Max: 100
  AutoCorrect: true
