default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # database: <%= Rails.application.credentials.dig(:aws, :RDS_DATABASE) %>
  # username: <%= Rails.application.credentials.dig(:aws, :RDS_USERNAME) %>
  # password: <%= Rails.application.credentials.dig(:aws, :RDS_PASSWORD) %>
  # host: <%= Rails.application.credentials.dig(:aws, :RDS_HOST) %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: pharmdv3_development

test:
  <<: *default
  database: pharmdv3_test
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

production:
  <<: *default
  database: pharmdv3_production
  username: pharmdv3
  password: <%= ENV["PHARMDV3_DATABASE_PASSWORD"] %>
# remote:
#   adapter: postgresql
#   database: <%= ENV['RDS_DATABASE'] %>
#   username: <%= ENV['RDS_USERNAME'] %>
#   password: <%= ENV['RDS_PASSWORD'] %>
#   host: <%= ENV['RDS_HOST'] %>
#   port: 5432
#   pool: 5
#   timeout: 5000
#   locale: en_US.UTF8
