name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode Google credentials
        run: |
          base64 --decode encoded_google_credentials.txt > config/credentials/pharmds-3a9649ca6677.json

      - name: Set environment variables
        run: |
          echo "GOOGLE_CREDENTIALS_PATH=config/credentials/pharmds-3a9649ca6677.json" >> $GITHUB_ENV

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Set up database
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}
        run: |
          bin/rails db:create db:schema:load

      - name: Run tests
        run: bundle exec rspec
